<?php

namespace AppBundle\Repository;

/**
 * TodoistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoistRepository extends \Doctrine\ORM\EntityRepository
{
}
